language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:xqms/opencv-nonfree
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cmake build-essential libopencv-dev libopencv-nonfree-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG

script: make -j 2

